# Generated by Django 4.2.9 on 2024-01-23 06:12

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_blog_category_blog_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_category',
            name='blog_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=100, unique=True),
        ),
    ]
