# Generated by Django 4.2.9 on 2024-01-23 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_blog_post_alter_blog_category_blog_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog_post',
        ),
    ]
