# Generated by Django 4.2.9 on 2024-01-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_blog_category_blog_summary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_category',
            name='blog_summary',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
