# Generated by Django 4.2.9 on 2024-01-30 05:46

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_alter_blog_category_blog_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blog_Name', models.CharField(max_length=100, unique=True)),
                ('blog_img', models.ImageField(upload_to='Cover/')),
                ('blog_summary', models.TextField(blank=True, max_length=200)),
                ('blog_description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.blog_category')),
            ],
        ),
    ]
