# Generated by Django 4.2.9 on 2024-02-01 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_blog_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes_id', models.IntegerField(default=0)),
                ('blog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.blog_post')),
            ],
        ),
    ]
