# Generated by Django 4.2.9 on 2024-02-01 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_add_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_likes',
            name='likes_id',
        ),
    ]
