# Generated by Django 4.2.9 on 2024-02-02 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_remove_add_likes_likes_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_views',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.blog_post')),
            ],
        ),
    ]
