# Generated by Django 4.2.9 on 2024-02-02 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_add_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='add_comments',
        ),
    ]
