# Generated by Django 4.2.9 on 2024-02-02 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_delete_add_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('blog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.blog_post')),
            ],
        ),
    ]
