# Generated by Django 4.2.9 on 2024-02-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_add_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_comments',
            name='username',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
